### ISSUE TITLE
Near interactions

### ISSUE THREAD

**Issue by kierepka** [provencher/MRTK-Quest-Sample#4]
Hi,
Thank you very much for your work! I am impressed with how much it brings to Oculus MRTK programming.
It seems to us that this example does not have the possibility of near interaction. Is it made on purpose or is it a bug?

greetings

**Comment by provencher** [comment]
Near interactions work with hands, but not controllers, because MRTK's official Oculus integration uses the existing controller interaction model, which is only for far rays.

If you want controller near-interaction, you can achieve that using my other repo - MRTK-Quest, which requires using a different device manager that has a custom solution for treating controllers as articulated hands.

https://github.com/provencher/MRTK-Quest
